#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

cd $OPENSHIFT_REPO_DIR
export CLUSTER=spark
echo "current cluster:$CLUSTER"
if [ "$CLUSTER" = "spark" ]
  then
    echo "init spark..."
    source ./spark-setup.sh
  else 
    if [ "$CLUSTER" = "hadoop" ]
    then
      echo "init hadoop..."
      source ./hadoop-setup.sh
    fi
fi
source ./autossh-setup.sh
